spring.application.name=backend
openai.api.key=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
